### ISSUE TITLE
handlebars helpers and partials as plugin/extension

### ISSUE THREAD

**Issue by chfw** [moremoban/moban-handlebars#12]
There exists handlebar helpers: 

https://handlebarsjs.com/guide/#block-helpers.

https://github.com/wbond/pybars3#implementation-notes

**Comment by chfw** [comment]
@CLiu13 are you interested in this?

**Comment by CLiu13** [comment]
Hmm, not particularly interested (been a while since I have worked on this), but if it is needed then I guess I can take a look - just let me know 👍

**Comment by chfw** [comment]
thanks for the reply. It seems that you have moved on. let's see if someone else would take it further.
